version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: db_maniaplanet_dev
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: JadoreLaBiereDansMonSac33000*!
      MYSQL_DATABASE: main_db
      MYSQL_USER: smserver
      MYSQL_PASSWORD: JadoreLaBiereDansMonSac33000*!
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  elite_server_01:
    build: .
    # image: llacoste2000/maniaplanet-server:0.3
    network_mode: host
    environment:
      - SERVER_NAME=aManiaplanetServer
      - DEDICATED_USERNAME=crunkserver1
      - DEDICATED_PASSWORD=LouJu2000
      - DATABASE_NAME=elite_server_01
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=JadoreLaBiereDansMonSac33000*!
      - MYSQL_ADDRESS=127.0.0.1
      - MYSQL_PORT=3306
      - XMLRPC_PORT=5000
    ports:
      - "2350:2350/tcp"
      - "2350:2350/udp"
      - "3450:3450/tcp"
      - "3450:3450/udp"
    volumes:
      - ./elite_server_01:/home/server

volumes:
  dbdata:
